### ISSUE TITLE
There's an issue with ...

### ISSUE THREAD

**Issue by walkr** [andreaantonioni/AAPhotoCircleCrop#2]
Ciao,

There is no issue. (:

I'm using this library in a project and I just wanted to say thank you for publishing this. 
I like how simple it is and how it does exactly what I wanted: simple circular image cropping.

Molte grazie!

**Comment by andreaantonioni** [comment]
This is a really open source way to say thank you 😅

Next time you can tweet me or send me an email 👍🏻
