### ISSUE TITLE
Cropping Landscape Images

### ISSUE THREAD

**Issue by Chefda** [andreaantonioni/AAPhotoCircleCrop#5]
Hi, i tested this project with landscape images. Project looks better with below revisions.

       var scaleWidth: CGFloat = 0
     
        if imageView.frame.width > imageView.frame.height
        {
            scaleWidth = scrollView.frame.size.height / scrollView.contentSize.height
        }
        else
        {
            scaleWidth = scrollView.frame.size.width / scrollView.contentSize.width
        }

      // Center vertically
        scrollView.contentOffset = CGPoint(x: (scrollView.contentSize.width - scrollView.frame.size.width)/2, y: (scrollView.contentSize.height - scrollView.frame.size.height)/2)

**Comment by andreaantonioni** [comment]
I'll check it ASAP, thank you :)

**Comment by andreaantonioni** [comment]
I forgot about this issue, sorry :(

I've improved cropping landscape images in `v1.3.0`, thank you 👍
